name: auth_repository
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  get: ^4.7.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/backgroundd.jpg
  image_dark: assets/images/backgroundd.jpg

  android_12:
    image: assets/images/backgroundd.jpg
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/backgroundd.jpg
    icon_background_color_dark: "#272727"

flutter:
  assets:
    - assets/images/backgroundd.jpg
    - assets/images/google.png
